// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  usageSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "starting/intro",
      },
      items: [
        {
          type: "doc",
          id: "starting/intro",
          label: "Introduction",
        },
      ],
    },
    {
      type: "category",
      label: "MatchMaker Example Workflows",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "use_cases/intro",
      },
      items: [
        {
          type: "doc",
          id: "use_cases/intro",
          label: "Introduction",
        },
      ],
    },
    {
      type: "category",
      label: "MatchMaker Vocabulary",
      collapsible: true,
      collapsed: true,
      link: {
        type: "doc",
        id: "vocab/intro",
      },
      items: [
        {
          type: "doc",
          id: "vocab/intro",
          label: "Introduction",
        },
      ],
    },
    {
      type: "doc",
      label: "MatchMaker FAQ",
      id: "faq/intro",
    },

    // {
    //   type: 'autogenerated',
    //   dirName: '.', // Auto-generates everything else
    // },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
